CONTIKI ?= ../../../../
CONTIKI_PROJECT = sensing

TARGET=cc26x0-cc13x0
BOARD=mirocard/cc2650
CFLAGS += -g

PLATFORMS_ONLY = cc26x0-cc13x0

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
