CFLAGS += -DBOARD_TRANSIENT=1

CONTIKI_TARGET_DIRS += transient

BOARD_SOURCEFILES += board.c board-buttons.c

MODULES += arch/dev/ext-fram

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1
