CFLAGS += -DBOARD_TRANSIENT=1

CONTIKI_TARGET_DIRS += transient


BOARD_SOURCEFILES += board.c board-buttons.c board-i2c.c
BOARD_SOURCEFILES += transient-sensors.c

MODULES += arch/dev/ext-fram
MODULES += arch/dev/am0815
MODULES += arch/dev/sht3x

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL = 1
