### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26xx

### Add to the source dirs
CONTIKI_TARGET_DIRS += transient-core/cc2650

### Include the common transient-core makefile
include $(PLATFORM_ROOT_DIR)/transient-core/Makefile.transient-core
