CFLAGS += -DBOARD_MIROCARD=1
CFLAGS += -DBACKDOOR_IOID=0x00000000

CONTIKI_TARGET_DIRS += mirocard common 

BOARD_SOURCEFILES += batteryless-sensors.c board-buttons.c sensor-common.c
BOARD_SOURCEFILES += opt-3001-sensor.c lis3dh-sensor.c
BOARD_SOURCEFILES += board.c board-i2c.c

MODULES += arch/dev/sht3x
MODULES += arch/dev/lis3dh

### Signal that we can be programmed with cc2538-bsl

BOARD_SUPPORTS_BSL = 1
