### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26x0

### Add to the source dirs
CONTIKI_TARGET_DIRS += mirocard/cc2650

### Include the common transient makefile
include $(PLATFORM_ROOT_DIR)/mirocard/Makefile.batteryless
